### ISSUE TITLE
Support ability to specify return values from previous LET statements in WHERE clause

### ISSUE THREAD

**Issue by alpeshgaglani** [codemix/oriento#178]
I want to write a (slightly contrived) query as follows:
```
db.let("userVertex", function(s){return s.select().from("User").where({name:"userone"})})
    .let("profileVertex", function(s){return s.select().from("Profile").where({user:"$userVertex"})
    .commit().all()
```
However, the second param gets sends $userVertex as a string value. If I write the raw SQL statement in a query, then things work fine. However it's not clean, and causes a lot of code duplication.

**Comment by phpnode** [comment]
Unfortunately there's no obvious, easy fix for this. It's a bit like the RID scenario where we'd need some kind of special object to signify a variable name, this is pretty horrible with RIDs and I don't want to add another one, at least not in this major version of Oriento. I've made a note of it in the todo list for 2.0 though.
