### ISSUE TITLE
Emoji characters are not saved correctly

### ISSUE THREAD

**Issue by amsul** [codemix/oriento#180]
Hey Charles,

I came across an issue when creating a vertex with a property that contains emoji.

It seems like an encoding issue (if you see square blocks, that's how your browser renders emoji):

```js
var query = 'CREATE VERTEX Post SET note = "testing emoji 💪💦👌"'
var results = yield database.query(query)
```

Which ends up creating the following post object with corrupted emoji data:

```js
{
  //...
  note: 'testing emoji ������'
}
```

**Comment by phpnode** [comment]
@amsul well that sucks, we have a [test specifically for emoji](https://github.com/codemix/oriento/blob/master/test/bugs/82-emojis.js) which passes on both `1.7.x` and `2.0-SNAPSHOT`. Please could you modify the test to make it fail?

Also, please confirm that the emoji are not getting corrupted before reaching Oriento, the bytes you've pasted here show as blocks in every browser I've tried, even browsers I know have no problem displaying emoji

**Comment by phpnode** [comment]
@amsul could not replicate this on either 1.7.10 or 2.0-SNAPSHOT, added a test for it [here](https://github.com/codemix/oriento/blob/master/test/bugs/82-emojis.js)

**Comment by amsul** [comment]
Hey Charles..thanks for the updated test case. I'm actually still on vacation till the end of this week - so i haven't had a chance to come around to this. Once I'll give it another shot n see if something outside of Oriento mucks it up.

Cheers!
