### ISSUE TITLE
Function execution isn't working correctly

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [codemix/oriento#185]
I am using orientdb 1.7 and i have created a simple stored function that insert data into a class. It is working in studio and Postman but not in oriento.
Function:
```
var gdb = orient.getGraph();

var user = User;
var ins = gdb.command('sql', 'insert into Category set name = "'+ user +'"');
return "success";
```
oriento:
```
db.select('addUser("'+ userName +'")').all().then(function(data) {
        console.log(data);
    });
```

It does returns 'success' but it doesn't insert data.

**Comment by AhtashamImtiyaz** [comment]
@phpnode any update about this issue?

**Comment by phpnode** [comment]
@AhtashamImtiyaz please try this- 
```js
db.exec('addUser("foo")').then(console.log.bind(console));
```

if you see `"success"` being returned then the bug is with OrientDB, not with Oriento

**Comment by AhtashamImtiyaz** [comment]
@phpnode but it is working perfectly with Postman.

**Comment by phpnode** [comment]
@AhtashamImtiyaz sadly that means nothing, the binary and REST protocols are very different and often produce inconsistent results. If you're comparing the results from REST and expecting the same via binary unfortunately you're out of luck

**Comment by phpnode** [comment]
@AhtashamImtiyaz i would also try changing the function to:
```js
var gdb = orient.getGraph();

var user = User;
gdb.command('sql', 'insert into Category set name = "'+ user +'"');
```

And inspect the result you get back. I'm pretty convinced this is an orientdb bug so I'm going to close it until proved otherwise. You could try filing an issue at https://github.com/orientechnologies/orientdb
