### ISSUE TITLE
record.resolveReferences() is vulnerable to duplicates

### ISSUE THREAD

**Issue by dmarcelino** [codemix/oriento#186]
...and this is a problem because OrientDB returns duplicates with fetch plan depth 2.

When `record.resolveReferences()` receives an array containing duplicate records it may fail to correctly replace IDs as there are multiple instances with same RID. I can think of 3 solutions to this issue:
1. Filter duplicates to prevent the issue from happening;
2. Convert `seen` from object to array so all instances are dealt with (may impact performance due to array lookups);
3. Convince the OrientDB folks not to send duplicates (may take longer).

This issue impacts both v1.7.10 and v2.0-RC1.

PS: I'll push tests and fixes soon.

**Comment by dmarcelino** [comment]
Hi @phpnode, I've pushed 2 different commits addressing solution 1. and 2. I'm unsure about if OrientDB is behaving as expected here. Even if there is an OrientDB issue, it can be a good idea not to propagate it to the user. Let me know what you think.

**Comment by phpnode** [comment]
closed via #187
