### ISSUE TITLE
Connection does not reset/reconnect if OrientDB is restarted.

### ISSUE THREAD

**Issue by tommys-place** [codemix/oriento#195]
Hi,

I found the case when OrientDB is restarted, active database connections does not reconnect any more so NodeJS instance have to be restarted.
I think that issue is with BinaryTransport.connect function from lib\transport\binary\index.js

When connection is lost, connection keeps previous promise which remembered rejected status so always returns without trying to reconnect

```javascript
{ '0':
   { [OrientDB.ConnectionError [ECONNREFUSED]: connect ECONNREFUSED]
     name: 'OrientDB.ConnectionError [ECONNREFUSED]',
     code: 'ECONNREFUSED',
     message: 'connect ECONNREFUSED',
     data: {} } }
```

I've changed to this and seems to be working ok.

```javascript
BinaryTransport.prototype.connect = function () {
  if (this.sessionId !== -1) {
    return Promise.resolve(this);
  }

  if (this.connecting) {
     if(this.connecting.isRejected()) {
         this.connection.emit('reconnectNow');
     } else {
         return this.connecting;
     }
  }

  ....
```

**Comment by phpnode** [comment]
@tommys-place thanks for the bug report, I fixed it slightly differently in #199 to avoid a possible race condition.
