### ISSUE TITLE
deserializer causes NodeJS to crash

### ISSUE THREAD

**Issue by tommys-place** [codemix/oriento#197]
Hi,

I've found another issue where Oriento causes FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory in NodeJS.

Error occurred when calling a query shown  bellow. In Studio  I get expected result, but through Oriento "invoice" and "credit" columns get only a list of virtual @rid's like [#-21:1, -21:2]
This array of virtual @rid's causes an infinitive loop in deserializer consuming all available NodeJS memory.

I don't know why  there are different results , maybe I'm doing it wrong so my workaround is to wrap in another select @this.toJSON().  

Still,  I think it should not crash server with infinitive loop because of minus operator.

```javascript
select @rid as invoiceID,  $tmp as invoice, $tmp2 as credit  from invoice
LET $tmp = (
            select $parent.$current.locationID as locationID, pricelist.@rid as pricelistID,  pricelist.code as code,  amount from (
              select expand(items) from $parent.$current
            )
           ), 
    $tmp2 = (
               select @rid as id, pricelist,  total, spent, remaining from (
      			select expand(out('HAS_CREDIT')) as credit from $parent.$current.locationID 
               )  
    	     )    
where status = 0 and  @rid = :invoiceID
```

To test it just execute this from oriento\lib\transport\binary\protocol28\

```javascript
var deserializer = require('./deserializer');

debugger;

var data = "@invoiceID:#23:8,invoice:[#-2:1],credit:[#-2:1,#-2:2,#-2:3,#-2:4]";

data = deserializer.deserialize(data);

console.log(data);
```

I've made a quickfix to prevent my server to crash, but rather to return invalid record.

```javascript
function eatRID (input) {
  var length = input.length,
      collected = '',
      cluster, c, i;

  for (i = 0; i < length; i++) {
    c = input.charAt(i);
    if (cluster === undefined && c === ':') {
      cluster = +collected;
      collected = '';
    }

    // !!! ADDED HERE MINUS OPERATOR CHECK !!!
    else if (c === '0' || c === '-' || +c) {
      collected += c;
    }
    else {
      break;
    }
  }

  return [new RID({cluster: cluster, position: +collected}), input.slice(i)];
}
```

**Comment by phpnode** [comment]
@tommys-place are you using the latest oriento from github? i fixed an issue similar to this the other day

**Comment by phpnode** [comment]
closing this, it was fixed a few days ago.

**Comment by tommys-place** [comment]
I've used 0.0.7, didn't realized there is 1.0.0 version :)) 
Thank you.
