### ISSUE TITLE
Inserting string value '+' produces error

### ISSUE THREAD

**Issue by petervc** [codemix/oriento#206]
If I execute the following (against orientdb-community-2.0-rc2):

db.insert().into(tableName).set({'test': '+'}).one();

produces the following error:

Possibly unhandled OrientDB.RequestError: Error on unmarshalling content. Class: com.orientechnologies.orient.core.sql.OCommandSQL

No error is produced if I use the browser interface to create a similar record.

**Comment by phpnode** [comment]
@petervc I [added a test](https://github.com/codemix/oriento/blob/master/test/bugs/206-insert-plus.js) for this but could not replicate. If you can make the test fail I'll reopen, thanks.

**Comment by petervc** [comment]
Looks like its fixed in orientdb-community-2.0 but still fails for me under orientdb-community-2.0-rc2.  Looking forward to Oriento 2.0!
