### ISSUE TITLE
generating 'is null' when using json in where clause

### ISSUE THREAD

**Issue by vishalkothari** [codemix/oriento#207]
Passing following JSON object as filter
whereClause = { obj1: null,
  obj2: '#15:0',
  obj3: null,
  subobj3: null }
to 
db.select().from(db.select().from('component').where(whereClause)).fetch({'*':1})

Results in following query.
executing query against db rapid: 
SELECT * FROM (SELECT * FROM component WHERE (obj1 = null AND obj2 = "#15:0" AND obj3 = null AND subobj3 = null))

obj1= null should be generated as obj1 is null for query to function.
Can you please provice information about how "is null" can be generated when filter criteria is provided using JSON object.

Regards,
Vishal Kothari

**Comment by phpnode** [comment]
@vishalkothari you can now pass `null` as a value in a "where object".
