### ISSUE TITLE
Query data event

### ISSUE THREAD

**Issue by orangemug** [codemix/oriento#208]
I'm interested in getting a log of query times back from oriento, my suggested approach would be to extend `lib/db/index.js` with an [event emitter](http://nodejs.org/api/events.html#events_class_events_eventemitter) and emit a "query" event with the query object and timing information.

Wrapping this line to capture timing info https://github.com/codemix/oriento/blob/73b6d9cce8b218d094f4737a4ede8ea44c582799/lib/db/index.js#L223 and emitting the object

    {
       perf: {
         queryTimes: MS_TIME_TAKEN
       },
       query: QUERY_OBJ_FROM_LN223
    }

Would you be interested in this as a feature? (I'm happy to work on it)

**Comment by phpnode** [comment]
Yes this is a great idea, but let's only do the measurement / emitting if there's actually a registered handler for the `query` event. PR would be very welcome!
