### ISSUE TITLE
transaction roll back more times

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#210]
anyone else who have any idea about "transaction roll back more times" issue?

**Comment by martingg88** [comment]
here is my code. I don't have any idea what cause about this issue since i'm only doing "Begin" once in a while.

BEGIN
LET user = INSERT INTO user SET email = "kk@gmail.com",
LET board = SELECT * FROM board WHERE title IN ["general","interest"]
LET task = CREATE EDGE task FROM $user TO $board SET ctime = "2015-01-26T11:31:06+0000", mtime = "2015-01-26T11:31:06+0000"
COMMIT
RETURN $user

**Comment by phpnode** [comment]
@martingg88 please could you create a test case which replicates the issue? it's hard to understand exactly what you mean from the info you've given so far.

**Comment by martingg88** [comment]
I'm using following query to sign up an account for user. If i try to submit the following code for many times and  then it may cause transaction roll back more times but this issue is not happen quite often. 

db.let('user', function(s){
   s.insert.into('user').set(data);
}).let('board', function(s){
  s.select().from('board').where("title IN ['general','interest']");
}).let('task', function(s){
s.create('EDGE' , 'task').from('$user').to('$board').set(data);
}).commit().return('$user')

**Comment by phpnode** [comment]
@martingg88 it's still not really clear what you mean, but from what I'm understanding it sounds like an OrientDB issue, it couldn't be Oriento related. It's worth copying one of the tests in `/test/bugs` and seeing if you can create a test case which reproduces the issue, as this will help clear up the issue and make sure it gets fixed faster. For now I'm going to close this, but will of course reopen if you submit a PR with a test.

**Comment by martingg88** [comment]
fyi.. Orientdb has solved this issue for OrientDB 2.0.1-SNAPSHOT
