### ISSUE TITLE
@rid is deleted when doing update/insert

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#214]
The @rid data is not stored into embedded type for following code.
 db.update(class).set({'@rid', '#12:36'})

**Comment by phpnode** [comment]
@martingg88 a few things wrong with this:

1. Embedded documents do not have RIDs
2. Your example code is updating a normal document, not an embedded document.
3. You're not wrapping your RID in an `Oriento.RID()` object, so it's being treated as a string.
4. OrientDB does not support setting the RID of a document, e.g. in studio this won't work
    ```sql
    update #5:2 set @rid = #5:20
    ```

**Comment by martingg88** [comment]
opsss...to be clarify on this issue. 

Actually, i'm trying to store the json data. i found out the following query will strip away @rid key even for storing it  in either string, document or both. 

db.update(class).set({'field' : {'anydata" : 'abc', @rid', '#12:36'}})

However, the following will work for orientdb database itself. 

update log set  field =  {'anydata" : 'abc', @rid', '#12:36'}
