### ISSUE TITLE
Add support for UPDATE operations other than SET in statements

### ISSUE THREAD

**Issue by ggoodman** [codemix/oriento#215]
As indicated on gitter, this issue recognizes that in `statement.js` there is only support for the `set()` operation. OrientDB supports the following additional operations: `INCREMENT|ADD|REMOVE|PUT`.

**Comment by dehbmarques** [comment]
Hi, Last week I was working on the ```PUT``` statement.

The idea is this:
```
db.update('#15:1')
  .put('embeddedmapProperty1', 'key1', 'value1')
  .put('embeddedmapProperty1', 'key2', 'value2')
  .put('embeddedmapProperty2', 'key3', { prop: 'val', createdAt: new Date() })
...
```

What do you guys think?

**Comment by ggoodman** [comment]
I think it would also make sense to accept an object as the 2nd argument to
add multiple puts if orientdb allows this.

**Comment by phpnode** [comment]
@dehbmarques @ggoodman I had similar ideas, PR would be very welcome :)

```js
db.update('#15:1').put('embeddedmapProperty1', 'key', 'value'); 
// or 
db.update('#15:1').put('embeddedmapProperty1', {'key': 'value'}); 
```

This is assuming that OrientDB supports multiple `PUT`s in the same statement, presumably it does I've not checked.

**Comment by dehbmarques** [comment]
Agreed, using the second as an object is better than add a ```.put()``` for each key.

OrientDB supports multiple ```PUT```s. It doesn't supports ```SET``` and ```PUT``` in the same statement. (tested using 2.0 version)

I'm going to create a pull request for this.

**Comment by dehbmarques** [comment]
Correcting, OrientDB only supports multiple ```PUT```s using different properties.

There is an open issue for that: https://github.com/orientechnologies/orientdb/issues/2665

**Comment by phpnode** [comment]
@ggoodman this should now be fixed

**Comment by kgreenpea** [comment]
Hi, the original request mentioned enhancement to include support for following operations, INCREMENT|ADD|REMOVE|PUT, I think just PUT support has been completed so far unless I'm missing something. Can the issue be reopened or these captured elsewhere? Thanks!

**Comment by phpnode** [comment]
@kgreenpea whoops, reopened, thanks.
