### ISSUE TITLE
:params becoming null

### ISSUE THREAD

**Issue by dehbmarques** [codemix/oriento#217]
@phpnode when I execute this statement
```
db.query('update #15:0 put accounts = "facebook", :param1', {
  params: {
    param1: {
      id: '000000',
      email: 'xxxx@xxxx.com'
    }
  }
});
```
the ```param1``` becomes ```null``` in OrientDB. The key ```facebook``` appears in the database but the value is set to ```null```.

In the ```orient-server.log``` (with the binary request log enabled) the statement looks ok.

```update #15:0 put accounts = "facebook", :param1  params: {"param1":{"id":"000000","email":"xxxx@xxxx.com"}}```

Do you know something about this issue? Looks like an OrientDB issue...

**Comment by phpnode** [comment]
@dehbmarques does the same thing happen when you inline the value (i.e. don't use bound params?)

**Comment by dehbmarques** [comment]
No, this works:
```
db.query('update #15:0 put accounts = "facebook", { "id": "000000", "email": "xxxx@xxxx.com" }');
// or
db.query('update #15:0 put accounts = "facebook", ' + JSON.stringify({ id: "000000", email: "xxxx@xxxx.com" }));
```

**Comment by phpnode** [comment]
definitely looks like an orientdb issue, one last thing to try:
```js
db.query('update #15:0 put accounts = "facebook", :param1', {
  params: {
    param1: {
      '@type': 'd',
      '@class': 'AccountOrWhateverTheEmbeddedClassIsCalled',
      id: '000000',
      email: 'xxxx@xxxx.com'
    }
  }
});
```

**Comment by dehbmarques** [comment]
It didn't work also.

I did the ```PUT``` statement support using params: https://github.com/dehbmarques/oriento/commit/44c8481e4eaae7d6098cb6fb44f5403e87bb98c2
But it's not working due this issue. I'm thinking in concat the params directly into the query using ```JSON.stringify()```.

What do you think?

**Comment by phpnode** [comment]
@dehbmarques as of #227 we no longer use OrientDB's parameter binding and instead do it ourselves. This issue should now be fixed and your `PUT` stuff should now work, without having to use `JSON.stringify()`, PR would be very welcome, thanks!

**Comment by dehbmarques** [comment]
Thanks
