### ISSUE TITLE
REST vs BINARY protocol

### ISSUE THREAD

**Issue by MarcelPitch** [codemix/oriento#224]
Hi @phpnode,

We continued the discussion about the difference between REST and Binary Protocol.

You're original issue : 
https://github.com/orientechnologies/orientdb/issues/3432

and a second one :
https://github.com/orientechnologies/orientdb/issues/3499

I'd like to know if you have any workaround for this problem.

It's a really basic query, and I think ther's something I'm missing cause I imagine your **oriento** users have had this same kind of problem.

Thanks

**Comment by phpnode** [comment]
@MarcelPitch I added a test for this in 6070785dca8cb35fb89b42e8f37c95f6ab6efe7a maybe I'm misunderstanding the issue but that seems to work as expected for me, and produces the same results as in the REST protocol. I'm going to close this for now but will be happy to reopen if you can provide some more detail about what you should expect to see (or ideally, make that test fail!), thanks!

**Comment by MarcelPitch** [comment]
Hi @phpnode,

Thank you for having investigate on my issue !!! :+1: 

OK, I've run your test and it fails :smile: !

I didn't tell you, but now I'm using **orientDB 2.0.1** and **oriento 1.0.1**.

I've this message :
```
OrientDB.RequestError: Error on parsing command at position #78: Invalid keyword '@RID'
Command: SELECT name, $DescendingPosts AS Posts FROM #11:0 LET DescendingPosts = SELECT @rid, message, score FROM (SELECT expand(out("WROTES")) FROM $parent.$current) ORDER BY  score DESC
```

It seems to be a problem with the sub-query ! I've remove the `@rid` in projection, and now it's `message` the invalid keyword.

I've run the same query in the **orientDB Studio**, and it fails to. But when adding '(' & ')' around the sub-query, it works.

But if it works on your machine, it's really promising !!!

**Comment by phpnode** [comment]
@MarcelPitch it's a bug in OrientDB that appears to have been fixed in 2.1-SNAPSHOT, my test fails on 1.7 and 2.0

**Comment by MarcelPitch** [comment]
Hi @phpnode,

OK, I've downloaded your **oriento 1.1.0**, and now it works !!!

It was just a problem of version !

Thanks @phpnode, have a nice day !

**Comment by phpnode** [comment]
@MarcelPitch great to hear that it's working now!
