### ISSUE TITLE
endQuery event should contain err

### ISSUE THREAD

**Issue by orangemug** [codemix/oriento#225]
The `endQuery` event should contain the error if it failed. The new `endQuery` event would be

    {
      "err": ErrObj
      "perf": {
        "query": timeInMs
      } 
    }

I'll take this one if you're happy with the API?

(I'll also add the missing entry in the README as a part of the fix)

**Comment by phpnode** [comment]
@orangemug yeah sounds good, PR would be awesome. For consistency think we should also add a `result` key with the query result when there's no error.
