### ISSUE TITLE
Field filtering does not handle substitutions

### ISSUE THREAD

**Issue by flipper53** [codemix/oriento#231]
Trying to filter an edge using a conditional operation on a field (http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Document-Field-Part.html) but nothing is being returned when using parameter substitution.

Using the following database:

````
----+-----+------+----------+----
#   |@RID |@CLASS|out_Drives|name
----+-----+------+----------+----
0   |#11:1|Person|[size=2]  |Fred
1   |#11:2|Person|[size=1]  |John
----+-----+------+----------+----

----+-----+------+-----+-----+----+---------
#   |@RID |@CLASS|make |model|vin |in_Drives
----+-----+------+-----+-----+----+---------
0   |#12:1|Car   |Volvo|XC 60|1234|[size=1] 
1   |#12:2|Car   |Volvo|XC 60|5678|[size=1] 
2   |#12:3|Car   |Tesla|S    |1111|[size=1] 
----+-----+------+-----+-----+----+---------
````

Selecting a car by VIN and Person from the console:

````
select expand( out( 'Drives' )[vin='1234'] ) from Person where name = 'Fred'

----+-----+------+----+-----+-----+---------
#   |@RID |@CLASS|vin |make |model|in_Drives
----+-----+------+----+-----+-----+---------
0   |#12:1|Car   |1234|Volvo|XC 60|[size=1] 
----+-----+------+----+-----+-----+---------
````

But I'm seeing different behaviour when applying parameters:

````javascript
var oriento = require( 'oriento' );

var server = oriento({
  host: 'localhost',
  port: 2424,

  username: 'root',
  password: 'root',
  logger: {
     debug: console.log.bind(console)
  }
});

var db = server.use('cars');

// returns record
db.query('select expand( out( "Drives" )[vin="1234"] ) from Person WHERE name = "Fred"',
		 {}
).then(function (response){
  console.log(response);
});

// returns record
db.query('select expand( out( "Drives" )[vin="1234"] ) from Person WHERE name = :name',
		 { params : { name: 'Fred' } }
).then(function (response){
  console.log(response);
});


// returns empty array
db.query('select expand( out( "Drives" )[vin=:v] ) from Person WHERE name = :name', { 
		 	params: {
		 		v : '1234',
		 		name: 'Fred'
		 	}
		 }
).then(function (response){
  console.log(response);
});

// Returns empty array
db.query('select expand( out( :d )[vin=:v] ) from Person WHERE name = :name', { 
		 	params: {
		 		d : 'Drives',
		 		v : '1234'
		 		name: 'Fred'
		 	}
		 }
).then(function (response){
  console.log(response);
});
````

Tested with oriento (1.0.0, 1.0.1) and orientdb (1.7.x,  2.0.1)

**Comment by phpnode** [comment]
@flipper53 please try with the latest version of Oriento from github, it's not on npm yet. This bug should have gone away (it's an OrientDB issue but we work around it)

**Comment by flipper53** [comment]
@phpnode No luck - got the latest from github (master branch) and still the same issue - is there another branch that should use?

**Comment by phpnode** [comment]
@flipper53 I was unable to replicate this in the latest version of Oriento with OrientDB 2.0+, I added a test for it [here](https://github.com/codemix/oriento/blob/master/test/bugs/231-field-filtering.js), if you can make the test fail I'll be happy to reopen this. Thanks!

**Comment by flipper53** [comment]
@phpnode My bad - was running the test of the github version in the wrong project directory - it fixed the issue - thanks for fixing the issue and releasing the new version. Great library for orientdb.

**Comment by phpnode** [comment]
@flipper53 no problem, glad you got it working!
