### ISSUE TITLE
Query builder for LET/FROM/TO clauses not supporting parameterized sub-query

### ISSUE THREAD

**Issue by mamobyz** [codemix/oriento#242]
LET/FROM/TO clauses also accept a builder function for building a sub-query. Though, it would be more helpful, if ```buildStatement()``` would preserve the parameterized queries. Currently, ```buildStatement()``` simply applies ```toString()``` to the returned sub-queries so that the parameters are directly bound to the string. This is a potential security threat since it is prone to SQL injections.

Although one can pass on the sub-queries as strings to the aforementioned clauses, but it is way to hard to provide unique parameter names, if you consider LET potentially can involve multiple independent queries which in turn can include multiple parameters.

It should be much easier for ```buildStatement()``` to count the total number of all parameters. So is there any chance to get this improved in the near future?

**Comment by phpnode** [comment]
@mamobyz there are many bugs with OrientDB's parameter binding implementation and therefore new versions of oriento avoid it entirely. This means that oriento is responsible for escaping / quoting values, I agree this is not ideal but it's something we've had to do until OrientDB fix their query parser (should be 2.1). Therefore it doesn't currently make sense for us to do what you're suggesting, but when those issues with OrientDB go away, I'll reopen this issue. Thanks.
