### ISSUE TITLE
'CREATE FUNCTION' API

### ISSUE THREAD

**Issue by orangemug** [codemix/oriento#245]
I have a helper written which I think belongs in core oriento. Basically the helper allows you to do the following

    var fnDef = createFn("log", function(num) {
      return Math.log(num);
    }); // => 'CREATE FUNCTION log "return Math.log(num);" PARAMETERS [num] LANGUAGE Javascript'
    db.query(fnDef);

I suggest we add this into the core, so the API would become

    db.createFn(METHOD_NAME, function([PARAMS]) {
       // FUNCTION BODY...
    });

It uses <https://www.npmjs.com/package/parse-function> underneath. I'll add a note to the README regarding not being able to use variables outside the closure.

I'm happy to send a PR if you're happy, thoughts?

**Comment by phpnode** [comment]
@orangemug yeah sounds great, probably don't even need the first parameter as we can extract `fn.name`

**Comment by orangemug** [comment]
@phpnode I think the first param is a better API. Given the following module

    // In `log.js`
    module.exports = function log(num) {
      return Math.log(num);    
    }

    // Used elsewhere
    var logFn = require("./log");
    db.createFn(logFn);

Your quite removed from the original function name in the above example, which is a little strange. Also function names aren't used that often in javascript in general because of the client side issues with minification and although thats not an issue here (because we're in node.js), it does make for an API that the majority of js dev won't have seen before.

Thoughts?

**Comment by phpnode** [comment]
@orangemug let's make it optional, 

```js
db.createFunction('foo', function bar () { });
// vs
db.createFunction(function bar () { });
```

**Comment by orangemug** [comment]
Yup cool, I'm happy with that.
