### ISSUE TITLE
Cannot create 4 edges at the same time

### ISSUE THREAD

**Issue by josegomezr** [codemix/oriento#253]
Im running this code (exactly like main docs):

```js
db.create('EDGE', 'E')
.from('#12:12')
.to('#12:13')
.one()
.then(function (edge) {
  console.log('created edge:', edge);
});
```

and I got this error `cannot UPDATE the record #X:Y because the version is not the latest ...`.

Im running OrientDB 2.0.2

**Comment by phpnode** [comment]
@josegomezr i've never seen that error, but it's certainly an orientdb bug, please file an issue at https://github.com/orientechnologies/orientdb

thanks
