### ISSUE TITLE
sql batch return invalid results

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#266]
it's doesn't return correct value if you have exapnd function in any select query. as for example below. it return the invalid result for user and payment, but except account.

BEGIN
LET account = SELECT * FROM account WHERE email = "ck@hotmail.com"
LET user = SELECT expand(in("own")) FROM account WHERE email = "ck@hotmail.com"
LET payment = SELECT EXPAND(out("own")[@class =payment]) FROM $user
COMMIT
RETURN [$account, $user, $payment]

[ 
{ '@type': 'd',
'@class': 'account',
email: 'ckgan2004@hotmail.com'
password: '00a8a1d8571d5cd2bf0
username: 'ckgan2004',
language: 'en',
timezone: 'Asia/Kuala_Lumpur',
active: false,
online: false,
ctime: Sun Feb 22 2015 20:45:0
mtime: Sun Feb 22 2015 23:08:1
nickname: 'ckgan2004',
'@rid': '#30:82' },
{ '@rid': '#5:0' },
{ classId: -2, value: null } 
]

**Comment by phpnode** [comment]
@martingg88 closing this because it's an OrientDB issue
