### ISSUE TITLE
Server.exist method not working due to case-sensitivity

### ISSUE THREAD

**Issue by mamobyz** [codemix/oriento#268]
When using Server.exist() for existence test on OSs with case-sensitive file systems, such as Linux, the method returns wrong result for Schemas with uppercase letters, e.g. myTestDb.

The code line https://github.com/codemix/oriento/blob/master/lib/server/index.js#L286 converts the schema name to lower case letters before testing, whereas use()/create()/drop() preserve the cases, refer to https://github.com/codemix/oriento/blob/master/lib/server/index.js#L185.

What do you think?

**Comment by phpnode** [comment]
closed via #269
