### ISSUE TITLE
Can't pass all config keys to create database

### ISSUE THREAD

**Issue by devspacenine** [codemix/oriento#272]
I am unable to set a username and password when creating a database. It looks like the create function is cutting out any config values other than "name", "type" and "storage".

https://github.com/codemix/oriento/blob/master/lib/server/index.js#L184

**Comment by phpnode** [comment]
@devspacenine OrientDB doesn't support this, you need to be connected to a server, and after you've created the database you can login and change the passwords for `admin`, `reader` and `writer`
