### ISSUE TITLE
How to create multiple properties in a single request?

### ISSUE THREAD

**Issue by codeniac** [codemix/oriento#278]
Do i really need to perform multiple create property requests to create multiple properties in a class? Isn't there a way to create all properties in only one request? I think that schema is a need (like in mongoose) even if the database is schema-less!!! :)

**Comment by phpnode** [comment]
@codeniac you can use an array of properties, e.g. `YourClass.property.create([{name:"a", type:"string"}, {name:"b", type:"string"}])`
