### ISSUE TITLE
stringify-ing a traverse() result

### ISSUE THREAD

**Issue by Ovidiu-S** [codemix/oriento#284]
When trying to use the data returned by a TRAVERSE query, the result cannot be stringify'ed, because it has a circular structure. 
I would rather not go trough the entire result set and remove all circular references.

waterline-orientdb uses 
.removeCircularReferences (object)

Can this be accomplished with oriento ?

**Comment by phpnode** [comment]
you might be able to use `oriento.jsonify(object)`, but it's not ideal. Alternatively you can use `db.exec()` rather than `db.query()` (if using the query builder, pass the query object to `db.exec`), and use the raw results directly.

**Comment by mrft** [comment]
Are here any helper functions that would help in turning the exec result into a result where the keys are replaced by the actual record (without creating circular structures, so only replace when not seen before) ?

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#20
