### ISSUE TITLE
Param double use bug

### ISSUE THREAD

**Issue by dvine-multimedia** [codemix/oriento#288]
Hi.

I have another weird one :)
Double use of a single parameter doesn't work. The weirdest thing: toString() shows the correct query.

This query doesn't work. The recipient = :id clause isn't set.
```javascript
DB
  .select()
  .from('Message')
  .where('(sender = :id or recipient = :id)')
  .addParam('id', userId)
```
The .toString() correctly shows 
`
SELECT * FROM Message WHERE (sender = #13:2 or recipient = #13:2)
`
though.

If you make two different parameters, it does work.
```javascript
DB
  .select()
  .from('Message')
  .where('(sender = :id1 or recipient = :id2)')
  .addParam('id1', userId)
  .addParam('id2', userId)
```

Cheers
Georg

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#19
