### ISSUE TITLE
db.delete() should be updated to 'DELETE VERTEX'

### ISSUE THREAD

**Issue by mikestaub** [codemix/oriento#289]
Since v2.0.0 of OrientDB, you cannot use DELETE to remove a vertex (unless you use UNSAFE), is there a way to delete a vertex this way in oriento? If not are there plans to update that functionality?

**Comment by dmarcelino** [comment]
Hi @mikestaub, you can use `db.delete('VERTEX')` to safely delete a vertex.

**Comment by mikestaub** [comment]
Thanks @dmarcelino ! I didn't see that anywhere in the docs, I should have guessed that was the solution

**Comment by dmarcelino** [comment]
@mikehaertl, no problem. It's actually on the README:
https://github.com/codemix/oriento#deleting-a-vertex
:wink:
