### ISSUE TITLE
Comma-separators missing in OrderBy-clause

### ISSUE THREAD

**Issue by mamobyz** [codemix/oriento#292]
With reference to issue #291, if an object argument with multiple attributes is passed on to statement.order(), the resulted orderBy-clause does not contain commas.

```
it('orders multiple fields', function(){
  this.statement.select().from('XYZ').order({field1:'', field2:'desc'});
  this.statement.toString().should.equal('SELECT * FROM XYZ ORDER BY field1, field2 desc');
});
```

Am I mistaking something?

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#17
