### ISSUE TITLE
Map empty collections to collections rather than NULL

### ISSUE THREAD

**Issue by mindplay-dk** [codemix/oriento#293]
Empty collections are currently mapped to `null` rather than to an empty collection.

For example, if a Person has a list of Tools, I expected `person.tools.forEach(...)` would work - but currently you need a guard clause around every collection traversal, e.g.:

    if (person.tools) {
        person.tools.forEach(...)
    }

Similarly, if you're going to add Tools to a Person, you would need a guard clause and then manually initializing the collection which seems like a lot of unnecessary boilerplate?

**Comment by phpnode** [comment]
@mindplay-dk the deserializer should handle this case correctly so I'd imagine OrientDB is sending `null` for empty collections, and we don't have type information so we have no way of knowing it should be converted to an empty set / list / map / whatever.

One way to get around this would be to use
```
db.registerTransformer("Person", function (doc) {
  // doc is a record with @class === "Person"
  doc.tools = doc.tools || [];
  return doc; // or you could cast to a JS class here
});
```
