### ISSUE TITLE
.exec works .query returns circular structure

### ISSUE THREAD

**Issue by mrft** [codemix/oriento#294]
You can easily check this on the GratefulDeadConcerts database.
<pre>
select name, $sungbyrecord as x_sungby 
from V 
let $sungby = outE()[ @class = 'sung_by' ], 
    $sungbyrecord = list( (select in.name, in.type from $sungby ) ) 
where name='HEY BO DIDDLEY'
</pre>

Executing this query using

<pre>orientodb.exec( q, {} ).then( ... ) // (or with a fetchPlan)</pre>

works but it returns a list of records with types "p" and "r" (p for the 'virtual' record $sungyrecord)
Since I want to have the result as 1 single javascript object, I should start puzzling this back together.

So I thought, maybe the orientodb.query method will do this for me, so I tried
<pre>orientodb.query( q, {} ).then( ... ) // (or with a fetchPlan)</pre>

But the result I get back seem to be
<pre>
[ { '@type': 'd',
    name: 'HEY BO DIDDLEY',
    x_sungby: [Circular],
    '@rid': { cluster: -2, position: 0 } } ]
</pre>
and if I util.inspect( records[0]?.x_sungby[0] ) I get the same, so instead of x_sungby being the proper subrecord containing name, type, it points back to the main record.

I think this is a bug. Using oriento 1.1.3.

**Comment by mrft** [comment]
On the other hand, this is quite understandable: since doing orientodb.**exec** returns

<pre>
[
  {
    "type": "p",
    "content": {
      "classId": 0,
      "type": "d",
      "cluster": -2,
      "position": 0,
      "version": 0,
      "value": {
        "@type": "d",
        "in": "Garcia",
        "in2": "artist"
      }
    }
  },
  {
    "type": "r",
    "content": {
      "classId": 0,
      "type": "d",
      "cluster": -2,
      "position": 0,
      "version": 0,
      "value": {
        "@type": "d",
        "name": "HEY BO DIDDLEY",
        "x_sungby": [
          "#-2:0"
        ]
      }
    }
  }
]
</pre>

Seems both have the same clusterid and position, so apart from the type (what do p and r stand for BTW?), there is no way to distinguish between the two.

So maybe this is an OrientDB bug? Or should oriento take the type into account?

**Comment by phpnode** [comment]
yes, the two results have the same record id, so it's an orientdb bug. `p` means prefetched - a document that is not part of the main result set but is returned because of a fetchplan or similar, `r` means record (this is the default for documents).
