### ISSUE TITLE
Params in SET subqueries don't work

### ISSUE THREAD

**Issue by dvine-multimedia** [codemix/oriento#296]
Hi everyone.

I'm not sure if this is an Oriento or an OrientDB issue.
In queris like:
```sql
DB.exec(
'INSERT INTO MyClass SET myProp = (select otherProp from OtherClass where @rid = :id)',
{
    params: { id: '#10:0' }
}
)
```
the :id param doesn't get resolved. Even though .toString() shows the correct query that works in studio.

Ideas?

Cheers
Georg

**Comment by phpnode** [comment]
it's an orientdb bug. If you use the query builder instead it will work
