### ISSUE TITLE
Inconsistency in DateTime going and coming values.

### ISSUE THREAD

**Issue by odiel** [codemix/oriento#300]
I'm not sure if this is an issue with Oriento or my lack of knowledge with JS:

Having the following code:

```
var datetime  = new Date();
var createdAt = datetime.toISOString();

console.log(createdAt);

db.insert().into('MyClass').set({id: someId, createdAt: createdAt}).one().then(function (event) {
            console.log(event.createdAt.toISOString());
});
```

Both console.log output are different from each other, does this has to do with the Date conversion somewhere?

**Comment by dmarcelino** [comment]
@odiel, try passing the date object `datetime` to `.set()` instead of the ISO string.

**Comment by phpnode** [comment]
yeah you must use `Date` instances, not strings, otherwise the driver cannot differentiate.

**Comment by odiel** [comment]
I was converting the Date to string since I don't see the milliseconds getting pass along to the DB. I need to keep fine track of the time. 

If I run the following query:

insert into MyClass content {id:"someId", createdAt: "2015-04-17 22:44:59.100"}

I can see OrientDB saves the information, but this is not happening using Oriento.

Is there any other way to get this done?

**Comment by dmarcelino** [comment]
@odiel, take a look at #204 changes, it should be easy to add milliseconds. Would mind doing a PR?

**Comment by odiel** [comment]
It looks pretty straight forward to add the changes. I'll do them once I
get some free time. Thanks.
