### ISSUE TITLE
UPDATE/SELECT records at same time

### ISSUE THREAD

**Issue by nomi-ramzan** [codemix/oriento#302]
Hi all !
How can we update or select multiple records at the same time( single query) ?
here is my question.
http://stackoverflow.com/questions/29446477/select-and-update-multiple-records-in-oriento

**Comment by seeden** [comment]
Please use
 
```js
db.update('#12:0').set({
  name: 'Zlatko'
}).return('AFTER @this');
```

**Comment by nomi-ramzan** [comment]
Hi Mr. Seeden 
How can I update multiple records on the same query ?
Like 
db.update({id:['#12:0','#12:1','#12:2','#12:3','#12:4']}).set({
  name: 'Zlatko'
}).return('AFTER @this');
