### ISSUE TITLE
Support Live Queries

### ISSUE THREAD

**Issue by tommykennedy** [codemix/oriento#304]
Hi 

Are there plans to support the new live queries feature in 2.1 ?

Regards,
Tom

**Comment by phpnode** [comment]
@tommykennedy @luigidellaquila has implemented support for this at https://github.com/luigidellaquila/oriento/tree/livequery i'm waiting for his PR

**Comment by luigidellaquila** [comment]
Hi @phpnode 

I'll do it very soon, but I'm afraid it requires a little review...
