### ISSUE TITLE
invalid result for let part. 

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#314]
There is the bug for following query as it is working fine on studio. 

SELECT *, $story as story FROM page
LET $story = (SELECT @rid as rid, url, metadata, done FROM story WHERE $current.page = $parent.current.@rid and $current.done = false ORDER BY metadata.release_date DESC) 

"story" must have return me the following result. 
[{"@type":"d","@rid":"#-2:113","@version":0,"rid":"#59:1074","url":"280107",@fieldTypes":"rid=x"}]

However it return me the invalid result as follow:
[ { [String: '#-2:83'] cluster: -2, position: 83 }]

**Comment by phpnode** [comment]
@martingg88 try using `.exec()` instead of `.query()`, do you get the same problem?

**Comment by martingg88** [comment]
i'm using the following method to retrieve the result.

                  db.select(util.format("*, $%s as %s", Story.identity, Story.identity))
                                .from(Page.identity)
                                .let('$' + Story.identity, util.format("SELECT %s as rid, %s, %s, %s FROM %s WHERE $current.page = $parent.current.@rid and $current.done = false ORDER BY metadata.release_date DESC",
                                Story.attributes['@rid'].columnName,
                                Story.attributes.url.columnName,
                                Story.attributes.metadata.columnName,
                                Story.attributes.done.columnName,
                                Story.identity))
                                    .transform(oriento.transform())
                                    .all()
                                    .then(function(result){

                                        console.log(result[0].story);

                                        callback(null, result);

                                    })
                                    .catch(function (err) {
                                        callback(err);
                                    })
                                    .done(function() {

                                    })

**Comment by phpnode** [comment]
try this:
```js
db.exec(db.select(util.format("*, $%s as %s", Story.identity, Story.identity))
                            .from(Page.identity)
                            .let('$' + Story.identity, util.format("SELECT %s as rid, %s, %s, %s FROM %s WHERE $current.page = $parent.current.@rid and $current.done = false ORDER BY metadata.release_date DESC",
                            Story.attributes['@rid'].columnName,
                            Story.attributes.url.columnName,
                            Story.attributes.metadata.columnName,
                            Story.attributes.done.columnName,
                            Story.identity))
                                .transform(oriento.transform())).nodeify(callback)
```


btw you're misusing promises in your example, rather than converting to callback manually, always use `somePromise.nodeify(callback)`

**Comment by martingg88** [comment]
i still have the same issue after tried your query here. any idea?

**Comment by phpnode** [comment]
@martingg88  can you paste the response you get back from the `.exec()` query?

**Comment by martingg88** [comment]
SELECT *, $story as story FROM page LET $story = (SELECT @rid as rid, url, metadata, done FROM story WHERE $
current.page = $parent.current.@rid and $current.done = false ORDER BY metadata.release_date DESC)

1. { status: { code: 0, sessionId: 142 },
  results: [ { type: 'l', content: [Object] }, payloadStatus: 0 ] }


2. decompose results[0].content to get the story as follow: 
[ { [String: '#-2:1'] cluster: -2, position: 1 },
  { [String: '#-2:2'] cluster: -2, position: 2 },
  { [String: '#-2:0'] cluster: -2, position: 0 },
  { [String: '#-2:3'] cluster: -2, position: 3 },
  { [String: '#-2:4'] cluster: -2, position: 4 },
  { [String: '#-2:6'] cluster: -2, position: 6 },
  { [String: '#-2:7'] cluster: -2, position: 7 },
  { [String: '#-2:5'] cluster: -2, position: 5 } ]

**Comment by phpnode** [comment]
@martingg88 if that's the only data coming back from `.exec()`, then it's an OrientDB bug. Please file an issue on [OrientDB's github](https://github.com/orientechnologies/orientdb/issues).

**Comment by martingg88** [comment]
can i know .exec() is for binary or http calling?

**Comment by phpnode** [comment]
everything is binary, http isn't really supported in this version

**Comment by martingg88** [comment]
thanks. i just file the issue at orientdb .
