### ISSUE TITLE
How to save large binary data using oriento on orientdb?

### ISSUE THREAD

**Issue by vjsrinath** [codemix/oriento#316]
I am trying to save image and video files directly in orientdb. After doing little bit of search, I saw the following documentation [Binary Data](http://orientdb.com/docs/last/Binary-Data.html). How to save bytes data using ORecordBytes with oriento.

Any help is appreciated. Thanks in advance.

**Comment by rmemoria** [comment]
+1... Same doubt

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#7
