### ISSUE TITLE
sql order parse issue.

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#319]
SELECT EXPAND(rid) FROM (SELECT story.release_date AS release_date, @rid FROM resource ORDER BY (release_date DESC, ctime DESC) LIMIT 15)

can we remove the bracket for order clause because it will have sql parse issue if we include more than one field in order bracket. 

(release_date DESC, ctime DESC)

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#5
