### ISSUE TITLE
db.record.delete("#1:1") makes dirty links.

### ISSUE THREAD

**Issue by SangWoo-Maeng** [codemix/oriento#320]
OrientDB 2.0.7

In graph mode DB, 
delete edge by rid like this.

db.record.delete('#1:1')
.then(function () {
  console.log('Record deleted');
});

The edge looks deleted but makes dirty links.
After execute that, in db console, repair database shows fixing links and docuements.

orientdb {db=test}> repair database
Repairing database...
- Fixing dirty links...Done! Fixed links: 2, modified documents: 2
Repair database complete (0 errors)

Dirty links, docs should not be made.

Please check it.

**Comment by StarpTech** [comment]
It seems like an orientdb issue. Please try via studio again.
```
DELETE VERTEX #1:1
```

**Comment by dmarcelino** [comment]
Have you tried using a syntax closer to the README example: https://github.com/codemix/oriento#deleting-an-edge-between-vertices? Something like:

```js
db.delete('EDGE')
.where('@rid = #1:1')
.one()
.then(function (count) {
  console.log('deleted ' + count + ' edges');
});
```

**Comment by SangWoo-Maeng** [comment]
I wanted to delete EDGE or VERTEX by RID regardless of its type.
So I tried to delete it such like this api 
db.record.delete('#1:1')

@StarpTech
I have multiple vertex and edges.
In the studio, the query specify the target type like this.
delete vertex #1:1
delete edge #2:2
These make no problem.

@dmarcelino  
From your mention, I understood that I have to use different API for each operation, deleting vertex or edge.

Thank you.

**Comment by dmarcelino** [comment]
> I wanted to delete EDGE or VERTEX by RID regardless of its type.

That's only possible if you force it by using the keyword `UNSAFE` on the query (I don't think Oriento has the syntax for this yet). More details on orientechnologies/orientdb#3163. Please note that using `UNSAFE` can potentially leave your graph in an inconsistent state.

You're welcome.

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#4
