### ISSUE TITLE
Question on vertex creation

### ISSUE THREAD

**Issue by kirankuppa** [codemix/oriento#322]
In my database, I consumer is a vertex and I am adding a new consumer record. I can accomplish this using the sql

1. create class consumer extends V
2. create vertex consumer set name="A1", user_id=1

I am trying to accomplish the same using oriento API. The docs give an example:

```
db.create('VERTEX', 'V')
.set({
  key: 'value',
  foo: 'bar'
})
.one()
.then(function (vertex) {
  console.log('created vertex', vertex);
});
```
Question 1 : Is this attempting to both create class (with name 'VERTEX' and extending 'V') as well as creating a record with keys ('key', 'foo')?

If so, having created the schema before hand which includes creating the vertex 'consumer', can I do the following to create a new record for consumer
```
db.create('consumer')
.set({
  name: 'A1',
  user_id: 1
})
.one()
.then(function (vertex) {
  console.log('created vertex', vertex);
});

```

**Comment by flyingrobots** [comment]
I think it would be:

```
db.create('VERTEX', 'consumer').set(/*...*/).one()
```

I could be wrong, though.

**Comment by yujinlim** [comment]
@kirankuppa this syntax should not create the class, it will generate this query `create vertex V set key="value", foo="bar"`, therefore it will fail if the class does not exists.

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#2
