### ISSUE TITLE
How to use createfn to retrieve record? 

### ISSUE THREAD

**Issue by ahtasham637** [codemix/oriento#323]
@phpnode how to use db.createFn to retrieve record from db? I tried this:
```
db.createFn("retreiveUser", function() {
      return db.query('select from User');
    })
    .then(function (data) {
          console.log(data);
    }).catch(function(err){
                console.log(err);
    });
```
But it isn't working

**Comment by phpnode** [comment]
@ahtasham637 `createFn` creates a function which runs on the server, Oriento itself is not available on the server so you can't use any of the API there. 
Once you've created your function you can select from it like anything else:
```js
await db.select("retrieveUser(123)").one();
```
