### ISSUE TITLE
Question: Accessing newly inserted values in batch mode

### ISSUE THREAD

**Issue by samuelgoldenbaum** [codemix/oriento#325]
How do I access the newly inserted @rid in my second batch statement. I need to be able to access the @rid from the first statement.

    var member = {
    	'email': 'test@test.com',
    	'id': 200,
    	'lastupdated': new Date()
    };
    
    db
    	.let('insert', function (s) {
    		s
    			.insert().into('member')
    			.set(member)
    	})
    	.let('update', function (s) {
    		s
    			.update('#12:74')
    			.set({
    				'from': '$insert'['@rid'] // how do I access the @rid from the previous statement
    			})
    	})
    	.commit()
    	.return('$update')
    	.all()
    	.then(function (results) {
    		console.log(results);
    	})
    	.done();

**Comment by phpnode** [comment]
Most/all the query builder methods allow you to use normal strings which form the query, so this should work:

```js
var member = {
    'email': 'test@test.com',
    'id': 200,
    'lastupdated': new Date()
};

db
    .let('insert', function (s) {
        s
            .insert().into('member')
            .set(member)
    })
    .let('update', function (s) {
        s
            .update('#12:74')
            .set("from = $insert") // <- now a string, not an object
    })
    .commit()
    .return('$update')
    .all()
    .then(function (results) {
        console.log(results);
    })
    .done();
```

**Comment by samuelgoldenbaum** [comment]
epic, thanks for that. Really very cool.

What about adding to a collection? 

I tried:

var member = {
    'email': 'test@test.com',
    'id': 200,
    'lastupdated': new Date()
};

db
    .let('insert', function (s) {
        s
            .insert().into('member')
            .set(member)
    })
    .let('update', function (s) {
        s
            .update('#12:74')
            .add('from', '=$insert')
    })
    .commit()
    .return('$update')
    .all()
    .then(function (results) {
        console.log(results);
    })
    .done();

but simply get ['=$insert','=$insert'] and not the values?

**Comment by phpnode** [comment]
try
```js
.add("from = $insert")
```

**Comment by samuelgoldenbaum** [comment]
unfortunately:

            throw e;
                  ^
OrientDB.RequestError: Error on parsing command at position #13: Expected keyword SET,ADD,CONTENT,MERGE,PUT,REMOVE,INCREMENT,LOCK or RETURN or UPSERT. Use UPDATE <class>|cluster:<cluster>> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {<JSON>}|MERGE {<JSON>}] [[,] <field-name> = <expression>|<sub-command>]* [LOCK <NONE|RECORD>] [UPSERT] [RETURN <COUNT|BEFORE|AFTER>] [WHERE <conditions>]
Command: UPDATE #12:98 ADD

**Comment by phpnode** [comment]
you might need to use a raw query, e.g.
```js
.let("update", "UPDATE #12:74 ADD from = $insert")
```

**Comment by samuelgoldenbaum** [comment]
works like charm - thanks Charles
