### ISSUE TITLE
newtork pools cause the cocurrent issue. 

### ISSUE THREAD

**Issue by martingg88** [codemix/oriento#331]
will have transaction roll back if you have more than one pool setup. 
i can send you a test script to prove this issue. 
lets me know how can i send you the test script.

**Comment by StarpTech** [comment]
please post the test script with the issue thanks

**Comment by martingg88** [comment]
set config.poo.max = 1 or 2 to see the issue. 

set config.username and config.password to your own.

Note: you have to npm install async for this test script. 


var path = require('path');
var async = require('async');


var oriento_lib_root = path.resolve(__dirname, '../../', 'lib');
var oriento_lib = require(oriento_lib_root);


var config = {
	  "host": "localhost",
	  "port": "2424",
	  "pool": {
		"max": 2
	  },
	  "transport": "binary",
	  "username": "root",
	  "password": "",
	  "database":{
		  "name": "testdb"
	  }
}


var TEST_SERVER = new oriento_lib.Server({
  host: config.host,
  port: config.port,
  username: config.username,
  password: config.password,
  transport: config.transport,
  pool: config.pool
});


var record = {
	  'name' : 'demo',
	  'metadata'  : {"genre":[],"budget":0,"translation":{"@type":"d","@version":0,"title":[]},"vote_average":0,"type":"trailer","production":{"@type":"d","@version":0,"company":[],"country":[]},"country":[{"name":null,"code":"US","date":""}],"title":"In Stereo","overview":"David and Brenda are perfect for each other, and everyone knows it except David and Brenda. After a break-up, they each experience their own rough patch. For David, a self-destructive artistic endeavor and a relationship with an immature beauty—for Brenda, a failing acting career, an eviction notice, and a boyfriend who just doesn’t do it for her. A chance encounter brings them together on the streets of New York at a particularly bad time. David invites Brenda to the opening of his first photography exhibit and the stage is set for a night of drinking and flirting which leads to an untraditional proposal of how they can be together without getting back together. A sharply observed, un-romantic comedy by writer/director Mel Rodriguez III, IN STEREO is a stylish and striking first feature that offers an unflinching look at the complexity of modern relationships.","source":{"@type":"d","@version":0,"imdb":"tt3478186","themoviedb":340189},"poster":"http://image.tmdb.org/t/p/original/QfnnGjCpvtJ0aY6IWKKnog2viF.jpg","release_date":"2015-07-03","language":"en","vote_count":0,"credit":{"@type":"d","@version":0,"crew":[],"actor":[]},"release":{"@type":"d","@version":0,"country":[{"name":null,"code":"US","date":"2015-07-03"}]},"popularity":0.159291,"revenue":0}
	};

describe('Database API', function () {

	before(function (done) {

			this.timeout(0);
			
			this.config = config;
			this.collections = {};
			
			this.db = '';
			this.class = '';
			this.rid = '';
			
			TEST_SERVER.create({
				name: this.config.database.name,
				type: 'graph',
				storage: 'plocal'
			  })
			  .bind(this)
			  .then(function(db) {
                
			
				 this.db = db;
				 
	
		
				(function (self){
					async.series([
					function(callback){
						self.db.class.create('test',  'V')
						.nodeify(function(err, item){
						
							if(err){
							  return callback(err);
							}
							
							self.class = item;
							
							callback();
						});

					},
					function(callback){
						self.class.property.create({
						  name: 'name',
						  type: 'String'
						})
						.nodeify(function(err, item){
						
							if(err){
							  return callback(err);
							}
							
							
							callback();
						});

					},
					function(callback){
						self.class.property.create({
						  name: 'metadata',
						  type: 'EMBEDDEDMAP'
						})
						.nodeify(function(err, item){
						
							if(err){
							  return callback(err);
							}
							
							
							callback();
						});

					},			
					function(callback){   
					  self.db.index.create({
						name: 'test.name',
						class: 'test',
						properties: 'name',
						type: 'FULLTEXT ENGINE LUCENE',
					  }).nodeify(function(err, index){
						
							if(err){
							  return callback(err);
							}
							
							
							callback();
						});  
					},			
					function(callback){   
					  self.db.index.create({
						name: 'test.metadata',
						class: 'test',
						properties: 'metadata',
						type: 'FULLTEXT ENGINE LUCENE',
					  }).nodeify(function(err, index){
						
							if(err){
							  return callback(err);
							}
							
							
							callback();
						});  
					},
					function(callback){
					  self.db
					  .insert()
					  .into('test')
					  .set(record)
					  .transform({
						'@rid': function (rid) {
							return '#' + rid.cluster + ':' + rid.position;
						}
					  })
					  .one()
					  .nodeify(function(err, result){

						 if(err){
							return callback(err);
						 }

						 self.rid = result['@rid'];
						 callback(null, result);
					  });

					}], function(err, result){
					
						 if(err){
							return done(err);
						 }
						 
						 done();
						 
					});
					
				}(this));
			  })
			  .catch(function(e) {
				done(e);
			})
		 
		  
	  });
  
	after(function (done){
	   
	  this.timeout(0);
	  
	  TEST_SERVER.drop({
	   name: this.config.database.name,
	   storage: 'plocal'
	 })
	 .bind(this)
	 .then(function () {
		done();
	 })
	 .catch(function(e) {
		done(e);
	 })
	})
  
	describe('Db::update()', function () {
		it('should have transaction rollback', function (done) {
	  
			  this.timeout(0);
			  
			  var parallel = [];
			  var max_try = 100;
			  for(i = 0; i < max_try; i++){

				   (function (self){
						parallel.push(function(callback){
						
								self.db.let('test', function(s){
									   s.insert().into('test').set(record);
								}).commit()
									 .return('$test')
									 .transform({
										'@rid': function (rid) {
											return '#' + rid.cluster + ':' + rid.position;
										}
									  })
									 .one()
									 .nodeify(function(err, result){

										if(err){
											return callback(err);
										}

										 callback(null, result);
									 });

						})
					}(this));
				
			  }

			  
			  async.parallel(parallel, function(err, result){
			  
				   if(err){

					 return done(err);
				   }
				   
				   done();
			  })
		  
		  
		});
    
	});

});

**Comment by martingg88** [comment]
lets me know if you have any issue about this test script. thanks

**Comment by phpnode** [comment]
@martingg88 unrelated to this particular issue but you're really making life hard for yourself by avoiding promises here, oriento was specifically designed to be used with promises. Compare your code above to the promise-driven equivalent:

```js
var Bluebird = require('bluebird');

var record = {
  'name' : 'demo',
  'metadata'  : {"genre":[],"budget":0,"translation":{"@type":"d","@version":0,"title":[]},"vote_average":0,"type":"trailer","production":{"@type":"d","@version":0,"company":[],"country":[]},"country":[{"name":null,"code":"US","date":""}],"title":"In Stereo","overview":"David and Brenda are perfect for each other, and everyone knows it except David and Brenda. After a break-up, they each experience their own rough patch. For David, a self-destructive artistic endeavor and a relationship with an immature beauty—for Brenda, a failing acting career, an eviction notice, and a boyfriend who just doesn’t do it for her. A chance encounter brings them together on the streets of New York at a particularly bad time. David invites Brenda to the opening of his first photography exhibit and the stage is set for a night of drinking and flirting which leads to an untraditional proposal of how they can be together without getting back together. A sharply observed, un-romantic comedy by writer/director Mel Rodriguez III, IN STEREO is a stylish and striking first feature that offers an unflinching look at the complexity of modern relationships.","source":{"@type":"d","@version":0,"imdb":"tt3478186","themoviedb":340189},"poster":"http://image.tmdb.org/t/p/original/QfnnGjCpvtJ0aY6IWKKnog2viF.jpg","release_date":"2015-07-03","language":"en","vote_count":0,"credit":{"@type":"d","@version":0,"crew":[],"actor":[]},"release":{"@type":"d","@version":0,"country":[{"name":null,"code":"US","date":"2015-07-03"}]},"popularity":0.159291,"revenue":0}
};

describe('Database API', function () {

  before(function () {
    this.timeout(0);

    this.config = config;
    this.collections = {};

    this.db = '';
    this.class = '';
    this.rid = '';

    return TEST_SERVER.create({
      name: this.config.database.name,
      type: 'graph',
      storage: 'plocal'
    })
    .bind(this)
    .then(function(db) {
      this.db = db;
      return db.class.create('test', V);
    })
    .then(function (testClass) {
      this.class = testClass;
      return testClass.property.create([
        {
          name: 'name',
          type: 'String'
        },
        {
          name: 'metadata',
          type: 'EMBEDDEDMAP'
        }
      ]);
    })
    .then(function () {
      return Bluebird.all([
        this.db.index.create({
          name: 'test.name',
          class: 'test',
          properties: 'name',
          type: 'FULLTEXT ENGINE LUCENE'
        }),
        this.db.index.create({
          name: 'test.metadata',
          class: 'test',
          properties: 'metadata',
          type: 'FULLTEXT ENGINE LUCENE',
        })
      ]);
    })
    .then(function () {
      return this.db
        .insert()
        .into('test')
        .set(record)
        .transform({
          '@rid': function (rid) {
              return '#' + rid.cluster + ':' + rid.position;
          }
        })
        .one()
    })
    .then(function (result) {
      this.rid = result['@rid'];
    });
  });

  after(function () {
    this.timeout(0);
    return TEST_SERVER.drop({
       name: this.config.database.name,
       storage: 'plocal'
     });
  });

  describe('Db::update()', function () {    
    it('should have transaction rollback', function () {
      this.timeout(0);
      var parallel = [];
      var max_try = 100;
      for(i = 0; i < max_try; i++){
        parallel.push(
          this.db.let('test', function (s) {
            s.insert().into('test').set(record);
          })
          .commit()
          .return('$test')
          .transform({
            '@rid': function (rid) {
              return rid.toString();
            }
          })
          .one()
        );
      }
      return Bluebird.all(parallel);
    });

  });
});
```

It's less than half as long!

**Comment by martingg88** [comment]
your script seems like doesn't work at all. it stop at  1) "before all" hook, any idea?

**Comment by phpnode** [comment]
probably because `config` etc not defined, i didn't run it.

**Comment by phpnode** [comment]
also if you're using an old version of mocha it could be related

**Comment by martingg88** [comment]
i tried to correct some syntax error from your script and it work now. But if you set the config.pool.max = 2. you will have transaction rollback issue. any idea?

var path = require('path');
var Bluebird = require('bluebird');

var oriento_lib_root = path.resolve(__dirname, '../../', 'lib');
var oriento_lib = require(oriento_lib_root);

var config = {
	  "host": "localhost",
	  "port": "2424",
	  "pool": {
		"max": 2
	  },
	  "transport": "binary",
	  "username": "root",
	  "password": "",
	  "database":{
		  "name": "testdb"
	  }
}

var TEST_SERVER = new oriento_lib.Server({
  host: config.host,
  port: config.port,
  username: config.username,
  password: config.password,
  transport: config.transport,
  pool: config.pool,
  useToken: true
});


var record = {
  'name' : 'demo',
  'metadata'  : {"genre":[],"budget":0,"translation":{"@type":"d","@version":0,"title":[]},"vote_average":0,"type":"trailer","production":{"@type":"d","@version":0,"company":[],"country":[]},"country":[{"name":null,"code":"US","date":""}],"title":"In Stereo","overview":"David and Brenda are perfect for each other, and everyone knows it except David and Brenda. After a break-up, they each experience their own rough patch. For David, a self-destructive artistic endeavor and a relationship with an immature beauty—for Brenda, a failing acting career, an eviction notice, and a boyfriend who just doesn’t do it for her. A chance encounter brings them together on the streets of New York at a particularly bad time. David invites Brenda to the opening of his first photography exhibit and the stage is set for a night of drinking and flirting which leads to an untraditional proposal of how they can be together without getting back together. A sharply observed, un-romantic comedy by writer/director Mel Rodriguez III, IN STEREO is a stylish and striking first feature that offers an unflinching look at the complexity of modern relationships.","source":{"@type":"d","@version":0,"imdb":"tt3478186","themoviedb":340189},"poster":"http://image.tmdb.org/t/p/original/QfnnGjCpvtJ0aY6IWKKnog2viF.jpg","release_date":"2015-07-03","language":"en","vote_count":0,"credit":{"@type":"d","@version":0,"crew":[],"actor":[]},"release":{"@type":"d","@version":0,"country":[{"name":null,"code":"US","date":"2015-07-03"}]},"popularity":0.159291,"revenue":0}
};

describe('Database API', function () {

  before(function () {
    this.timeout(0);

    this.config = config;
    this.collections = {};

    this.db = '';
    this.class = '';
    this.rid = '';

    return TEST_SERVER.create({
      name: this.config.database.name,
      type: 'graph',
      storage: 'plocal'
    })
    .bind(this)
    .then(function(db) {
      this.db = db;
      return db.class.create('test', 'V');
    })
    .then(function (testClass) {
      this.class = testClass;
      return testClass.property.create([
        {
          name: 'name',
          type: 'String'
        },
        {
          name: 'metadata',
          type: 'EMBEDDEDMAP'
        }
      ]);
    })
    .then(function () {
      return Bluebird.all([
        this.db.index.create({
          name: 'test.name',
          class: 'test',
          properties: 'name',
          type: 'FULLTEXT ENGINE LUCENE'
        }),
        this.db.index.create({
          name: 'test.metadata',
          class: 'test',
          properties: 'metadata',
          type: 'FULLTEXT ENGINE LUCENE',
        })
      ]);
    })
    .then(function () {
      return this.db
        .insert()
        .into('test')
        .set(record)
        .transform({
          '@rid': function (rid) {
              return '#' + rid.cluster + ':' + rid.position;
          }
        })
        .one()
    })
    .then(function (result) {
      this.rid = result['@rid'];
    });
  });

  after(function () {
    this.timeout(0);
    return TEST_SERVER.drop({
       name: this.config.database.name,
       storage: 'plocal'
     });
  });

  describe('Db::update()', function () {    
    it('should have transaction rollback', function () {
      this.timeout(0);
      var parallel = [];
      var max_try = 100;
      for(i = 0; i < max_try; i++){
        parallel.push(
          this.db.let('test', function (s) {
            s.insert().into('test').set(record);
          })
          .commit()
          .return('$test')
          .transform({
            '@rid': function (rid) {
              return rid.toString();
            }
          })
          .one()
        );
      }
      return Bluebird.all(parallel);
    });

  });
});

**Comment by martingg88** [comment]
are you able to reproduce the issue? let me know what cause this issue if you have any idea. if the issue is from orientdb itself then i can deal with orientdb team member. thanks.

**Comment by StarpTech** [comment]
Oriento is no longer maintained. Please post this issue in the official nodejs driver OrientJs repo https://github.com/orientechnologies/orientjs

@phpnode correct?

**Comment by phpnode** [comment]
@StarpTech not sure yet, they make some bold promises in that article, waiting to see if they can deliver. They're welcome to the bugs though, so yes please reopen this issue there.

**Comment by martingg88** [comment]
@phpnode is it safe to migrate OrientJs driver since oriento is not going to be maintained?

**Comment by dmarcelino** [comment]
Personal opinion: I still hope Oriento is not forked into OrientJS, more about it in https://github.com/orientechnologies/orientdb/issues/4354#issuecomment-112967647

**Comment by phpnode** [comment]
@martingg88 I'm not going to recommend that anyone switches to orientjs right now, at the moment orientjs is just oriento renamed, I would wait until they actually ship something before making that decision

**Comment by lucaolivari** [comment]
@martingg88 thanks for opening the first issue on the orientjs driver! We appreciate that and we've actively allocated resources to improve it, building on the excellent work done by @phpnode -- Read my comments here: https://github.com/orientechnologies/orientdb/issues/4354#issuecomment-113129571

**Comment by martingg88** [comment]
@lucaolivari. thanks for sharing this. i'm regret to tell you that i dun want to be involved in this quarrel. I'm most concerned on how the issue can be solved as soon as possible. 

Here are some of my experiences for orientdb database that i have been using for a year. 
1. i have realized the current version of orientdb is not stable and promising yet. In that case i really spent a lot of time to debug your stuffs more than doing my own thing. Since here, i really hope we can have most stable version as same as MYSQL in future. 
2. A good software should treat testing procedure seriously before release it to market. As for orientdb version releasing that always brings up a lot of issues (etc: bugs) and thus these glitch will cause serious issue to any application especially for the one which involve payment processing. 

Finally, i'm look forward your team can look into these issues that i have mentioned in this post. in between, i'm really appreciated the efforts of your team have contributed to this Orientdb database. Thanks.
