### ISSUE TITLE
Inserting a record with value for "LINK" data type

### ISSUE THREAD

**Issue by rajeshvaya** [codemix/oriento#332]
As inserting a record with data type "LINK" of a field we need to pass for e.g. #12:11 as a value but the library makes it as "#12:11" (with quotes) and the insert query fails

e.g. 

```
System.db.insert().into('loyalty').set({
  'link_field_name' : '#12:11'
})
```

**Comment by phpnode** [comment]
@rajeshvaya you need to wrap your record id in a RID instance, otherwise oriento treats it as a string.
```js
var RID = Oriento.RID;
System.db.insert().into('loyalty').set({
    link_field_name: new RID('#12:11')
})
```
