### ISSUE TITLE
Add support for uuid / tree based RIDBag

### ISSUE THREAD

**Issue by phpnode** [codemix/oriento#5]
Currently only the simpler 'embedded' [RIDBag](https://github.com/orientechnologies/orientdb/wiki/RidBag) type is supported. We need to also support the tree based type.

**Comment by dmarcelino** [comment]
@phpnode, please disregard the tests I've added concerning this issue. They are a separate issue covered by #186. Cheers

**Comment by phpnode** [comment]
This issue was moved to orientechnologies/orientjs#29
